name: Deploy Developmnt version-control-backend

on:
  push:
    branches:
      - master-development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH to EC2 and pull latest code
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/html/dev/Version-Control-Frontend
          # Pull the latest code using your configured deploy key
          sudo -E env "GIT_SSH_COMMAND=ssh -i /home/ubuntu/.ssh/id_rsa" git pull origin master-development
          # Install dependencies
          sudo npm install
          # Restart the app
          pm2 restart version-App-dev
        EOF
